### ISSUE TITLE
`NoClassDefFoundError` when running instrumented tests with newrelic-android-agent 7.2.0 on project with `paho.mqtt.android` dependency

### ISSUE THREAD

**Issue by jbduncan** [newrelic/newrelic-android-agent#158]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

(This issue is a follow-up to https://support.newrelic.com/s/case-details?caseId=5008W00001AFoxBQAT, which was raised and closed back in August 2023, with little indication when it will be fixed, so I'm re-raising it here for visibility and to see if there's anything I can do to speed things along.)

We are unable to upgrade newrelic-android-agent from 6.6.0 to 7.2.0 (newest version at time of writing) because of a `NoClassDefFoundError` that appears w.r.t. https://github.com/eclipse/paho.mqtt.android, a dependency of our app, when running our instrumented tests.

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

When using `com.newrelic.agent.android:agent-gradle-plugin:7.2.0` with app dependencies `org.eclipse.paho:org.eclipse.paho.client.mqttv3` and `org.eclipse.paho:org.eclipse.paho.android.service` and running the instructions under section "Steps to Reproduce", we get a `NoClassDefFoundError`.

This is preventing us from updating from 6.6.0 to 7.2.0, and in turn preventing us from updating to Gradle 8 and Android Plugin for Gradle (AGP) 8, because NewRelic 6.6.0 uses an API that was deprecated and removed in Gradle 8 / AGP 8.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. Download the attached zip file, which contains a minimal example project.
2. Open it in Android Studio Giraffe or newer.
3. Start up any Android emulator running on Android 24 or greater.
4. Run `./gradlew connectedCheck`.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

The test `ExampleInstrumentedTest.useAppContext()` passes.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

When running the test, it fails with the following message.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/eclipse/paho/client/mqttv3/IMqttAsyncClient;
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.eclipse.paho.client.mqttv3.IMqttAsyncClient" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.example.myapplication.test-HbwxoTNIju97rvU5XCP6xQ==/base.apk", zip file "/data/app/com.example.myapplication-aq_-y8SpeZLD9ushMjzvyA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication.test-HbwxoTNIju97rvU5XCP6xQ==/lib/arm64, /data/app/com.example.myapplication-aq_-y8SpeZLD9ushMjzvyA==/lib/arm64, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 34 more
```

Also, the stack trace below is reported in Android Studio Logcat.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/eclipse/paho/client/mqttv3/IMqttAsyncClient;
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
    at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
    at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
    at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.eclipse.paho.client.mqttv3.IMqttAsyncClient" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~6mR07S1zWhawa70WOId_iA==/com.example.myapplication.test-aNYPTJL2yySHx8EzgxXmPg==/base.apk", zip file "/data/app/~~PPGQOWilH67QSY39WfLkcg==/com.example.myapplication-VCKaKXHmuik0CtzWhPxXkg==/base.apk"],nativeLibraryDirectories=[/data/app/~~6mR07S1zWhawa70WOId_iA==/com.example.myapplication.test-aNYPTJL2yySHx8EzgxXmPg==/lib/arm64, /data/app/~~PPGQOWilH67QSY39WfLkcg==/com.example.myapplication-VCKaKXHmuik0CtzWhPxXkg==/lib/arm64, /system/lib64, /system_ext/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at java.lang.reflect.Constructor.newInstance0(Native Method) 
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250) 
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260) 
    at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309) 
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
    at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306) 
    at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) 
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) 
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) 
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) 
    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
    at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
    at org.junit.runners.Suite.runChild(Suite.java:128) 
    at org.junit.runners.Suite.runChild(Suite.java:27) 
    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
    at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67) 
    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58) 
    at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446) 
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* macOS Ventura 13.6
* Java 17
* Android Studio Giraffe or newer
* Any Android emulator running Android 24 or greater

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

Attachment: [MyApplication.zip](https://github.com/newrelic/newrelic-android-agent/files/13561913/MyApplication.zip)

**Comment by cthomas-newrelic** [comment]
@jbduncan Thank you for the supporting material. It really goes a long way in diagnosing odd issues such as this. I would have requested a debug-enabled build log, but your repro case should be sufficient. Apologies for the disconnect with your support ticket. I do recall seeing this come across but thought it had been picked up by another eng.

**Comment by cthomas-newrelic** [comment]
As submitted, your test fails with agent version 7.0.0, but is successful with 7.1.0 and higher, called out in the 7.1.0 [release notes](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/android-release-notes/android-710/). The dependency `org.eclipse.paho.client.mqttv3-1.2.5.jar` is signed, so for now the agent plugin will now avoid the problem until more complete solutions. It is called out in the `7.2.0` debug build log: 
```
[ClassTransform] Excluding signed or incompatible artifact[/Users/cthomas/.gradle/caches/modules-2/files-2.1/org.eclipse.paho/org.eclipse.paho.client.mqttv3/1.2.5/1546cfc794449c39ad569853843a930104fdc297/org.eclipse.paho.client.mqttv3-1.2.5.jar]from instrumentation
```
Please let us know if you see this in final apps.
