### ISSUE TITLE
ANR when start AmFirebaseListenerService

### ISSUE THREAD

**Issue by ahmedmuhammedpro** [newrelic/newrelic-android-agent#197]
when run on Android 14 i got this ANR crash

FATAL EXCEPTION: main
Process: com.nahdi.main, PID: 5348
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f11d574 u0 com.nahdi.main/com.appmanago.lib.fcm.AmFirebaseListenerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2315)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2286)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2611)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2023)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1967)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:847)
	at com.nahdi.main.presentation.ui.activity.splash.SplashActivity.n0(SplashActivity.kt:6)
	at com.nahdi.main.presentation.ui.activity.splash.SplashActivity.onCreate(SplashActivity.kt:3)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Activity.performCreate(Activity.java:8913)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6493)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6377)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:68)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6453)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2695)
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:230) 
	at android.os.Looper.loop(Looper.java:319) 
	at android.app.ActivityThread.main(ActivityThread.java:8893) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by ndesai-newrelic** [comment]
@ahmedmuhammedpro is it still the issue?

**Comment by ywang-nr** [comment]
Close the issue and reopen as needed.
